### ISSUE TITLE
views exposed filter not working anymore?

### ISSUE THREAD

**Issue by bcfirst** [signalpoint/DrupalGap#580] opened 2015-07-05 13:17 UTC
Views exposed filter was working great according to http://www.drupalgap.org/node/498. But then views is not sending the same jason output any more ( some additional data is not showing up that existed before I can't figure out why that happended ) therefore the exposed filter is not being rendered correctly on the app and only displays the apply button.

**Comment by signalpoint** [comment] 2015-07-05 14:13
@bcfirst Can you please provide example JSON before and after to show what is happening here?

**Comment by bcfirst** [comment] 2015-07-06 14:46
![1](https://cloud.githubusercontent.com/assets/13186230/8524947/cddf5c08-2406-11e5-8171-ecdc2db2f451.JPG)

This is the JSON that is currently being sent.... I couldn't get the working json output , But if  I remember correctly there was additional data being sent after the one in the image.

**Comment by signalpoint** [comment] 2015-07-07 15:06
@bcfirst The `filter` array should definitely not be empty. I wonder if the latest release of `Views` has changed the way filters are stored, and DrupalGap no longer grabs them properly. The place to debug this will be in the `drupalgap_preprocess_views_views_json_style_simple()` function in this file: http://cgit.drupalcode.org/drupalgap/tree/drupalgap.module

**Comment by nithinkolekar** [comment] 2015-07-28 07:20
@signalpoint 
Normal List fields with static key|value pair are working fine and problem is only with term reference field. Will check why filter array is empty only for term reference field..

**Comment by nithinkolekar** [comment] 2015-07-28 18:50
In my setup also `filter[]` is not setting in views preview UI for taxonomy term field :(.
Sorry couldn't find the cause by rollbacking diffrent modules. I think only way is  someone who has the working exposed filter setup  would share exact modules list with their version. 
Based on my observation views or views json are causing this.

**Comment by nithinkolekar** [comment] 2015-07-30 09:29
also created issue [exposed form filter array empty for term reference field but works fine with list field](https://www.drupal.org/node/2542548) at [Views Datasource.](https://www.drupal.org/project/views_datasource)
@bcfirst would you share info about with which module version it was working before?

**Comment by nithinkolekar** [comment] 2015-07-31 16:40
@signalpoint 

> I wonder if the latest release of Views has changed the way filters are stored, and DrupalGap no longer grabs them properly

nope.. I found that DrupalGap   7.x-1.9 and DrupalGap   7.x-1.10 is working fine with latest views too. Only with and after 7-.x-1.11 is causing filter not populated.Here are the module versions with which it is working fine.
Drupal core 7.38
Views 3.8
Views JSON  7.x-1.0-alpha2
DrupalGap   7.x-1.9 ,DrupalGap  7.x-1.10

also moved issue created at DO to [drupalgap](https://www.drupal.org/node/2542548)

**Comment by stvx** [comment] 2015-08-01 13:54
I also had problems with views exposed filter with recent versions of drupal.  Then I downgraded drupal to 7.26 and its working perfect now..

**Comment by nithinkolekar** [comment] 2015-08-03 07:40
@stvx 
what Druaplgap version did worked with drupal 7.26 and also from which version did you downgraded?  This will help module developer/contributors to identify the cause and try to fix it.

**Comment by stvx** [comment] 2015-08-03 09:55
@nithinkolekar If im not mistaken I was using the version of drupal, 7.x-1.0-rc5 , @signalpoint How can I check the version for a confirmation?

**Comment by signalpoint** [comment] 2015-08-03 13:27
@stvx You should be able to check your index.html file, and look at the file name for the drupalgap include. That should include the version number (unless you were using a dev snapshot of just the bin/drupalgap.js file).

**Comment by signalpoint** [comment] 2015-08-03 13:51
@nithinkolekar  I'm sure you know, but Drupal 7.26 is extremely un-secure and you should not be using it. Views is up to 3.11 now

**Comment by nithinkolekar** [comment] 2015-08-03 18:13
This table will explain more than words.. 

| Drupal Core | DrupalGap SDK | Views | [DrupalGap Module](https://www.drupal.org/node/1414540/release?api_version[]=103) | Worked |
| --- | --- | --- | --- | --- |
| 7.38 | Latest dev from github | 3.11 | 7.x-1.13 | No |
| 7.38 | Latest dev from github | 3.10 | 7.x-1.13 | No |
| 7.38 | Latest dev from github | 3.8 | 7.x-1.13 | No |
| 7.38 | Latest dev from github | 3.11 | 7.x-1.12 | No |
| 7.38 | Latest dev from github | 3.10 | 7.x-1.12 | No |
| 7.38 | Latest dev from github | 3.8 | 7.x-1.12 | No |
| 7.38 | Latest dev from github | 3.11 | 7.x-1.11 | No |
| 7.38 | Latest dev from github | 3.10 | 7.x-1.11 | No |
| 7.38 | Latest dev from github | 3.8 | 7.x-1.11 | No |
| 7.38 | Latest dev from github | 3.11 | 7.x-1.10 | **Yes** |
| 7.38 | Latest dev from github | 3.10 | 7.x-1.10 | **Yes** |
| 7.38 | Latest dev from github | 3.8 | 7.x-1.10 | **Yes** |
| 7.38 | Latest dev from github | 3.11 | 7.x-1.9 | **Yes** |
| 7.38 | Latest dev from github | 3.10 | 7.x-1.9 | **Yes** |
| 7.38 | Latest dev from github | 3.8 | 7.x-1.9 | **Yes** |
| 7.38 | Latest dev from github | 3.11 | Below 7.x-1.9 | Not supported |
| 7.38 | Latest dev from github | 3.10 | Below 7.x-1.9 | Not Supported |
| 7.38 | Latest dev from github | 3.8 | Below 7.x-1.9 | Not Supported |

**Comment by signalpoint** [comment] 2015-08-04 02:38
@nithinkolekar thank you for this table, that is incredibly useful information. I've reviewed the git logs and nothing jumps out as a suspect. Will you please add `watchdog('drupalgap', '<pre>' . print_r($vars['view']->filter, true) . '</pre>');` to before this line?

http://cgit.drupalcode.org/drupalgap/tree/drupalgap.module?id=fac9addfbdbc73a8a809f422316ecd2218ca0225#n312

I'm curious what, if anything, is being reported in the filters for the view.

**Comment by nithinkolekar** [comment] 2015-08-04 17:45
@signalpoint  Before testing with above code I just checked which version is it? I seems code at cgit is not same as dev or 7.13 at DO.

So I downloaded all files in the cgit to test with the watchdog code and surprisingly exposed filters are showing. Because that watchdog array was huge I didn't posted here.

I guess code available at DO is not updated one from cgit ?

**Comment by signalpoint** [comment] 2015-08-04 20:56
@nithinkolekar I'm glad to hear that it is working now, however I'm not sure what you mean by "cgit"? Will you please share URL(s) related to your findings? Thanks.

**Comment by nithinkolekar** [comment] 2015-08-05 20:15
@signalpoint 
sorry for not sharing proper url , just mentioned cgit instead of complete http://cgit.drupalcode.org path which is referred as code repository I guess(?). 
I had downloaded all files from http://cgit.drupalcode.org/drupalgap/tree/?id=fac9addfbdbc73a8a809f422316ecd2218ca0225 one by one as there are few files.

**Comment by mkinnan** [comment] 2015-08-29 18:09
I can also verify that going from Drupalgap 7.x-1.13 to 7.x-1.10 made the views filter appear. Now 

```
"filter" : []
```

is not empty with 7.x-1.10.

**Comment by coolman7** [comment] 2015-09-01 14:05
There are a lot of comments, I could not catch. So what's the latest status? Is it working with latest versions? Or should we use older versions?

Thanks

**Comment by signalpoint** [comment] 2015-10-19 14:39
@nithinkolekar @mkinnan @coolman7 @stvx @bcfirst Hello all, I believe I just found the bug that was causing this. It should be fixed with this commit: http://cgit.drupalcode.org/drupalgap/commit/?id=2ff34b7

Grab the latest dev snapshot of the DrupalGap Drupal Module for this fix.

**Closed as completed by signalpoint** 2015-10-19 14:39 UTC
Labels: Support Request, 7.x-1.x

**Comment by mkinnan** [comment] 2015-10-23 00:04
@signalpoint Latest dev version appears to fix the issue. Thanks!
