### ISSUE TITLE
When i click on the Node page tittle the page is redirect on the node full page in drupalgap.

### ISSUE THREAD

**Issue by sanee** [signalpoint/DrupalGap#125] opened 2013-08-06 11:55 UTC
plese help me .

**Comment by signalpoint** [comment] 2013-08-06 13:33
@sanee - Sorry, I don't understand. Where are you clicking on a node page title? If you are clicking on a node title from the default content list that is provided with DrupalGap, it should automatically redirect you to the full page view of the node in DrupalGap, this is by design.

If you are viewing a node in DrupalGap, and there is a link to another node in your node body, then that link will not load the node in DrupalGap. This is a known 'bug', it just hasn't been documented yet.

Please be more specific with your issue though. What pages, platform, and development environment are you using? Thanks.

**Comment by signalpoint** [comment] 2013-08-13 03:17
Now that I think about it, the 'bug' mentioned above isn't a bug at all. It's just what is in the node's body and DG can't control that. Instead I'd recommend a contrib module for DG that would rewrite the node body to properly link to nodes within the app and properly display an images etc. That would be a beneficial contrib module indeed.

**Comment by signalpoint** [comment] 2013-08-18 00:10
#137

**Comment by signalpoint** [comment] 2013-09-03 17:56
@sanee - the fix for this has been rolled into a contrib module for DrupalGap:

http://www.drupalgap.org/project/pathfix

Update to the latest 7.x-1.x-alpha snapshot for this fix (or wait until 7.x-1.6-alpha is out).

Thanks for motivating this issue!

**Closed as completed by signalpoint** 2013-09-03 17:56 UTC
Labels: Support Request
