### ISSUE TITLE
"node_page_view" referenceError: nid is not defined

### ISSUE THREAD

**Issue by hkvega01** [signalpoint/DrupalGap#41] opened 2013-05-08 09:12 UTC
i' just created a drupalgap apps & installed everything. But when i click "content" to read a node, it prompt a error message sequence
Drupalgap API Error | "{}"
Alert | "node_page_view" referenceError: nid is not defined, 
Drupalgap API Error | "{}"
Alert | menu_execute_active_handler(node/2) - TypeError: Cannort set property 'pageshow' of undefined

What are the problems?

**Comment by scotthooker** [comment] 2013-05-13 23:14
Also having above problem.

**Comment by signalpoint** [comment] 2013-05-13 23:30
Sorry, I'm not able to reproduce this bug and will need more information.

First, will you please verify your Node Retrieve resource is setup correctly on your site by doing a GET with Firefox Poster on a URL like this?

http://www.example.com/drupalgap/node/93.json

If I understand correctly, you are clicking the 'Content' tab, then when your content list loads, you click on one of the items to view the node (e.g. node/2)? Correct?

Please make sure the 'debug' value in your settings.js file is set to true and review the console log information in Eclipse. I'd be curious to see what it says.

We'll be looking for debug information about the call to your site (http://www.example.com/drupalgap/node/93.json), it should explain what the response code is.

Are you using the Alpha version?

**Comment by signalpoint** [comment] 2013-06-23 02:17
@scotthooker & @hkvega01 , were you able to resolve this issue you were having? There has been many bug fixes in the Alpha branch in the last month. This one should be fixed. If it isn't, on your Drupal site, check the drupalgap_content view to make sure it is returning a nid and title in its results.

**Comment by scotthooker** [comment] 2013-06-23 10:43
For me this problem was on the drupal side of things and wasn't an issue with DrupalGap I can't remember exactly what it was but something along the lines of the nid was invalid.

**Comment by scotthooker** [comment] 2013-06-23 10:43
So yes all resolved for me.

**Closed as completed** 2013-06-24 03:39 UTC
Labels: Bug
