### ISSUE TITLE
image uploading but showing as currpted

### ISSUE THREAD

**Issue by gireeshscs** [signalpoint/DrupalGap#666] opened 2015-11-19 06:25 UTC
I have used file_save image saving happening, but got corrupted on display . if we open the image it shows. Error interpreting JPEG image file (Improper call to JPEG library in state 200)

can anyone help me to fix this.please help

**Comment by signalpoint** [comment] 2015-11-19 13:30
Duplicate of #665

**Closed as completed by signalpoint** 2015-11-19 13:30 UTC
Labels: Support Request, 7.x-1.x
