### ISSUE TITLE
Anonymous users menu stays after login

### ISSUE THREAD

**Issue by 1nf1n7y** [signalpoint/DrupalGap#732] opened 2016-02-26 11:56 UTC
the following steps lead to the problem:
1. the user status is logged in when initializing the app.
2. the user click on logout
3. the user clicked on login in and he entered his credentials. and successfully logged in.
4. the user clicked logout again.
and the anonymous users menu showed up instead of authenticated users menu.
![1](https://cloud.githubusercontent.com/assets/9547879/13353017/6e39ec3c-dca2-11e5-8afe-65bc172b1097.JPG)
![2](https://cloud.githubusercontent.com/assets/9547879/13353021/73b61a3c-dca2-11e5-8de9-93c7c4a5b6ff.JPG)

**Comment by mkinnan** [comment] 2016-02-28 00:24
Is this a duplicate of:

https://github.com/signalpoint/DrupalGap/issues/680

https://github.com/signalpoint/DrupalGap/issues/621

**Closed as completed** 2016-02-28 02:43 UTC

**Comment by 1nf1n7y** [comment] 2016-02-29 15:06
I confirm that the problem was solved by adding reloadPgae : true argument to drupagap_goto in login and logout functions in drupalgap.js file ... as the following:
`function user_logout_pagechange() {
  try {
    user_logout({
      success: function(data) {
        drupalgap_goto(drupalgap.settings.front,{reloadPage: true});
      }
    });
  }
  catch (error) { console.log('user_logout_pagechange - ' + error); }
}`

`function user_login_form_submit(form, form_state) {
  try {
    user_login(form_state.values.name, form_state.values.pass, {
      success: function(result) {
        drupalgap_goto(drupalgap.settings.front,{reloadPage: true});
      }
    });
  }
  catch (error) { console.log('user_login_form_submit - ' + error); }
}`
